# Generated by Django 6.0.2 on 2026-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_created_at_customuser_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSTDateTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_datetime', models.DateTimeField()),
            ],
        ),
    ]
