# Generated by Django 6.0.2 on 2026-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_pstdatetimerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pstdatetimerecord',
            old_name='pst_datetime',
            new_name='datetime_pst',
        ),
        migrations.AddField(
            model_name='pstdatetimerecord',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
